services:
  swagger-editor:
    image: swaggerapi/swagger-editor:v4.9.1
    platform: linux/amd64
    container_name: "swagger-editor"
    ports:
      - "8001:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui:v4.18.3
    platform: linux/amd64
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - docs/api.yaml:/reference/api.yaml
    environment:
      SWAGGER_JSON: /reference/api.yaml

  swagger-api:
    image: stoplight/prism:5.0.0
    platform: linux/amd64
    container_name: "swagger-api"
    ports:
      - "9000:4010"
    command: mock -h 0.0.0.0 /reference/api.yaml
    volumes:
      - docs/api.yaml:/reference/api.yaml

  # openapi-generator:
  #   image: openapitools/openapi-generator-cli:v6.6.0
  #   container_name: "openapi-generator"
  #   volumes:
  #     - docs/api.yaml:/reference/api.yaml
  #     - ./api-skeleton/:/api-skeleton/
